export const ASYNC_START = 'ASYNC_START';
export const ASYNC_END = 'ASYNC_END';

export const SET_AUTH = 'SET_AUTH';
export const SET_CUR_POS = 'SET_CUR_POS';

export const INIT_STATE = 'INIT_STATE';
export const SET_LICENCE = 'SET_LICENCE';
export const SET_SELECTED_LICENCE = 'SET_SELECTED_LICENCE';
export const UPDATE_LICENCE = 'UPDATE_LICENCE';
export const SAVE_CONTACT_DETAILS = 'SAVE_CONTACT_DETAILS';
export const SET_INSURANCE = 'SET_INSURANCE';
export const SET_DEGREE = 'SET_DEGREE';
export const SET_CERT = 'SET_CERT';
export const SET_SELECTED_CERT = 'SET_SELECTED_CERT';
export const SET_SELECTED_EXP = 'SET_SELECTED_EXP';
export const SET_PAGE_VISITED = 'SET_PAGE_VISITED';
export const SET_SELECTED_STATES = 'SET_SELECTED_STATES';
export const SET_LOCATIONS = 'SET_CURRENT_LOC';
export const SET_JOB_TYPE = 'SET_JOB_TYPE';
export const SET_EXPS = 'SET_EXPS';
export const SET_SHOW_EXTEND = 'SET_SHOW_EXTEND';
export const SET_DEGS = 'SET_DEGS';
export const SET_CERTIFICATIONS = 'SET_CERTIFICATIONS';

export const SET_ROLE = 'SET_ROLE';
export const SET_EMAIL = 'SET_EMAIL';
export const SET_ABOUTUS = 'SET_ABOUTUS';
export const SET_HOSP_LOCATIONS = 'SET_HOSP_LOCATIONS';
export const SET_HOSP_CONTACTS = 'SET_HOSP_CONTACTS';
export const SET_HOSP_DETAILS = 'SET_HOSP_DETAILS';

export const SET_HP_PROFILE = 'SET_HP_PROFILE';
export const SET_SP_PROFILE = 'SET_SP_PROFILE';
export const SET_TEMP_FILE = 'SET_TEMP_FILE';